apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: proc-dataweave
  namespace: kns
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/mrkunkel/proc-dataweave
